app/microblog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, EqualTo, Email, ValidationError, Length
from app import db
import sqlalchemy as sa
from app.models import User
from flask_babel import lazy_gettext as _l, _
from flask import request

class PostForm(FlaskForm):
    post = TextAreaField(_l('Say Something!'), validators=[Length(min=1, max=140)])
    submit = SubmitField(_l('Submit'))

    def validate_post(self, post):
        if not post.data.strip():
            raise ValidationError(_('Post cannot be blank!'))

class ResetPasswordRequestForm(FlaskForm):
    email = StringField(_l('Email'), validators=[DataRequired(), Email()])
    submit = SubmitField(_l('Request Password Reset'))

class ResetPasswordForm(FlaskForm):
    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

    password = PasswordField(_l('Enter New Password'), validators=[DataRequired(), Length(min=8)])
    password_confirm = PasswordField(_l('Please Confirm your New Password'), validators=[EqualTo('password'), DataRequired()])
    submit = SubmitField(_l('Reset Password'))

    def validate_password(self, password):
        if password.data.find(self.user.username)>=0:
            raise ValidationError(_('Password is not allowed to contain your username.'))
        
        if self.user.check_password(password.data):
            raise ValidationError(_('Your new password cannot be the same as the current one.'))
        
class SearchForm(FlaskForm):
    q = StringField(_l('Search'), validators=[DataRequired()])

    def __init__(self, *args, **kwargs):
        if 'formdata' not in kwargs:
            kwargs['formdata'] = request.args
        if 'meta' not in kwargs:
            kwargs['meta'] = {'csrf':False}
        super(SearchForm, self).__init__(*args, **kwargs)

app/microblog/__init__.py
from flask import Blueprint

bp = Blueprint('microblog', __name__)

from app.microblog import routes

app/microblog/routes.py
from app import db
from flask import render_template, flash,redirect, url_for, request, g, jsonify, current_app
from flask_login import login_required, current_user
from app.main.forms import EmptyForm
import sqlalchemy as sa
from app.models import User, Post, TechStack
from app.shared_functions import text_linkification
from datetime import datetime
from flask_babel import _, get_locale
from langdetect import detect, LangDetectException
from app.translate import translate
from app.microblog import bp
from app.microblog.forms import SearchForm, PostForm
import re

@bp.before_request
def before_request():
    if current_user.is_authenticated: 
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
        g.search_form = SearchForm()
    g.locale = str(get_locale())

@bp.route('/', methods=['GET','POST'])
@bp.route('/index', methods=['GET','POST'])
@login_required
def index():
    persistentMsg = ''
    form = PostForm()
    if form.validate_on_submit():
        if not current_user.isVerified:
            flash(_('Please confirm your email from Profile'))
            return redirect(url_for('microblog.index'))
        try:
            language = detect(form.post.data)
        except LangDetectException:
            language =''
        form.post.data = text_linkification(form.post.data)
        post = Post(body=form.post.data, author=current_user, language=language)
        db.session.add(post)
        db.session.commit()
        flash(_('Your post is now live!'))
        return redirect(url_for('microblog.index'))
    page = request.args.get('page', default=1, type=int)
    posts = db.paginate(current_user.followed_posts_select().order_by(Post.timestamp.desc()), 
                        page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    next_url=url_for('microblog.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url=url_for('microblog.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('microblog/index.html', title=_('Home'),  posts = posts, form = form, next_url=next_url, prev_url=prev_url)

@bp.route('/explore')
def explore():
    form = EmptyForm()
    page = request.args.get('page', default=1, type=int)
    posts = db.paginate(sa.select(Post).order_by(Post.timestamp.desc()),
                        page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    next_url = url_for('microblog.explore', page=posts.next_num) if posts.has_next else None
    prev_url = url_for('microblog.explore', page=posts.prev_num) if posts.has_prev else None
    return render_template('microblog/index.html', title=_("Explore"), posts = posts.items, next_url=next_url, prev_url=prev_url, form=form)

@bp.route('/delete/<postID>', methods=["POST"])
@login_required
def delete(postID):
    form = EmptyForm()
    if form.validate_on_submit():
        post = db.session.get(Post, postID)
        if post is None:
            flash(_('The post you deleted could not be found'))
            return redirect(request.referrer)
        post.delete()
        db.session.commit()
        flash(_('You have successfully deleted the post!'))
        return redirect(request.referrer)
    else:
        return redirect(url_for('microblog.index'))
    
@bp.route('/translate', methods=['POST'])
@login_required
def translate_text():
    return jsonify({'text': translate(request.form['text'],
                                      request.form['source_language'],
                                      request.form['dest_language'])})    

@bp.route('/search')
@login_required
def search():
    if not g.search_form.validate():
        return redirect(url_for('microblog.explore'))
    page = request.args.get('page', 1, type=int)
    posts, total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
    next_url = url_for('microblog.search', q=g.search_form.q.data, page=page+1) if total > page * current_app.config['POSTS_PER_PAGE'] else None
    prev_url = url_for('microblog.search', q=g.search_form.q.data, page=page-1) if page > 1 else None
    form = EmptyForm()
    return render_template('search.html', title=_('Search'), posts=posts, next_url=next_url, prev_url=prev_url, form=form)

app/templates/microblog/_post.html
<div class="postTable">
    <div class="d-flex mb-2">
        <div class="flex-shrink-1 me-2 postAvatar">
            <img class="avatarImg" src = "{{ post.author.avatar(36) }}">
        </div>
        <div class="flex-grow-1">
            {% set user_link %}
            <a href = "{{ url_for('main.user', username=post.author.username) }}">
                {{ post.author.username }}
            </a> 
            {% endset %}
                {{ _('%(username)s said %(when)s:', 
                    username=user_link, when = moment(post.timestamp).fromNow()) }}  
            <span id="post{{ post.id }}" class="text-break microblogPost">
                {{ post.body|textile|safe }}
            </span>
            {% if post.language and post.language != g.locale %}
                {% if current_user.is_authenticated %}
                <span id="translation{{ post.id }}" class="text-break">
                    <a href="javascript:translate(
                        '#post{{ post.id }}',
                        '#translation{{ post.id }}',
                        '{{ post.language }}',
                        '{{ g.locale }}');">{{ _('Translate') }}
                    </a>
                </span>
                {% endif %}
            {% endif %}
        </div>
        <!--3 dot contextual menu-->
        {% if current_user.is_authenticated %}
        <div class="flex-shrink-1">
            <div class ="dropdown">
                <a class="dropdown-toggle" id="postDropDownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="postDropDownMenuLink">
                    {% if current_user == post.author %}
                    <li><a class="dropdown-item" href="#deleteModal{{ post.id }}" data-bs-toggle="modal">{{ _('Delete') }}</a></li>
                    {% elif current_user.is_authenticated and current_user.is_following(post.author) %}
                    <form action="{{ url_for('main.unfollow', username=post.author.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value=_("Unfollow " + post.author.username), class="dropdown-item") }}
                    </form>
                    {% elif current_user.is_authenticated and not current_user.is_following(post.author) %}
                    <form action="{{ url_for('main.follow', username=post.author.username) }}" method="post">
                        {{ form.hidden_tag() }}
                        {{ form.submit(value=_("Follow " + post.author.username), class="dropdown-item") }}
                    </form>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% endif %}
    </div>
</div>
<!--Delete Modal-->
<div class="modal fade" id="deleteModal{{ post.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">{{ _('Confirm Delete') }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
            </div>
            <div class="modal-body">
                {{ _('Are you sure you want to delete this post?') }} <br><br>
                <div class="vr"></div>
                <div class="text-break">{{ post.body}}</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _('Close') }}</button>
                <form action="{{ url_for('microblog.delete', postID = post.id) }}" method="post">
                    {{ form.hidden_tag() }}
                    {{ form.submit(value=_('Delete'), class="delete btn btn-outline-danger") }}
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/microblog/index.html
{% extends "base.html" %}

{% block content %}
    {% if current_user.is_authenticated %}
    <h1>{{ _('Hi, %(username)s!', username=current_user.username) }}</h1>
    {% endif %}

    {% if form.post %}
    <p>
        <form action="" method="post">
            {{ form.hidden_tag() }}
            <div class="form-floating mb-3">
            {{ form.post(class="form-control", id="floatingPost", placeholder="Say Something!") }}
            {{ form.post.label(for="floatingPost") }}
            </div>
            {% for error in form.post.errors %}
            <span style="color:red;">{{ error }}</span><br>
            {% endfor %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                {% if not current_user.isVerified %}
                <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#msgModal">Submit</button>
                {% elif current_user.isVerified %}
                {{ form.submit(class="btn btn-outline-primary") }}
                {% endif %}
            </div>
        </form>
    </p>
    {% endif %}
    <br>
    {% for post in posts %}
        {% include "microblog/_post.html" %}
    {% endfor %}
    <br>
    {% include "_pagination.html" %}
    <!--Modal for Users without confirmed email-->
    <div class="modal fade" id="msgModal" tabindex="-1" aria-labelledby="msgModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="msgModalLabel">{{ _('Email Confirmation Required') }}</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
                </div>
                <div class="modal-body">
                    {{ _('Please confirm your email from the Profile Page before posting') }} <br><br>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _('Close') }}</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}