app/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Length, Email, ValidationError, Optional
from flask_ckeditor import CKEditorField
from flask_babel import lazy_gettext as _l, _
from app import db
import sqlalchemy as sa
from app.models import User


class BlogPostForm(FlaskForm):
    title = StringField(_('Title'), validators=[DataRequired(), Length(min=1, max=90)])
    body = CKEditorField(validators=[DataRequired(), Length(min=1, max=37000)])
    tags = StringField(_('Tags (Separate by a comma and a space. E.g. Tag1, Tag2):'), validators=[DataRequired()])
    series = StringField(_('Series'),validators=[Length(max=100)])
    seriesOrder = IntegerField(_('Series Order'), validators=[Optional()])
    save = SubmitField(_l('Save to Drafts'))
    submit = SubmitField(_l('Submit'))

class CommentForm(FlaskForm):
    username = StringField(_('Name'),  validators=[DataRequired(), Length(min=1, max=64)])
    email = EmailField(_('Email'), validators=[DataRequired(), Email()])
    comment = TextAreaField(_('Comment'),  validators=[DataRequired(), Length(min=1, max=140)])
    submit = SubmitField(_l('Submit'))
    
    def validate_username(self, username):
        user = db.session.scalar(sa.select(User).filter_by(username=username.data))
        if user is not None:
            raise ValidationError(_('Username already exists! Please choose another name'))
   

app/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__)

from app.blog import routes

app/blog/routes.py
from app.blog import bp
from app.blog.forms import BlogPostForm, CommentForm
from app.main.forms import EmptyForm
from app.shared_functions import text_linkification, anonymous_avatar
from app import db, cache
from flask_login import current_user
from flask import flash, redirect, url_for, render_template, request, current_app, g, session
from flask_babel import _
from app.models import Article, Tag, Comment
import sqlalchemy as sa
from datetime import datetime

@bp.before_request
def before_request():
    g.all_tags = get_all_tags()
    current_app.jinja_env.globals.update(anonymous_avatar=anonymous_avatar)

def tag_article(article, strTags):
    for tag in strTags:
        if tag:
            tag = tag.strip()
            t = db.session.scalar(sa.Select(Tag).filter_by(name=tag))
            if not t:
                t = Tag(name=tag)
                db.session.add(t)
            article.tag(t)

def get_all_tags():
    all_tags = cache.get('all_tags')

    if all_tags:
        return all_tags

    all_tags = db.session.scalars(Tag.fetch_all_tags().order_by(Tag.name)).all()
    return all_tags

def get_articles_with_tags_series():
    articles_with_tags = cache.get('articles_with_tags')
    series_with_articles = cache.get('series_with_articles')

    if articles_with_tags and series_with_articles:
        return articles_with_tags, series_with_articles 

    articles = db.session.scalars(Article.fetch_submitted()).all()
    
    articles_with_tags={}
    series_with_articles = {}

    for article in articles:
        for tag in db.session.scalars(article.tags.select()).all():
            if article.id not in articles_with_tags:
                articles_with_tags[article.id] = [tag.name.strip()]
            else:
                articles_with_tags[article.id].append(tag.name.strip())
        if article.series and article.series not in series_with_articles:
            series_with_articles[article.series] = list(db.session.scalars(Article.fetch_all_series(article.series).order_by(
                Article.seriesOrder)).all()) 

    cache.set('articles_with_tags', articles_with_tags, timeout=3600)
    cache.set('series_with_articles', series_with_articles, timeout=3600)
    return articles_with_tags, series_with_articles

@bp.route('/', methods=['GET','POST'])
@bp.route('/index', methods=['GET','POST'])
def index():
    
    emptyForm = EmptyForm()
    page = request.args.get('page', default=1, type=int)
    articles = db.paginate(Article.fetch_submitted().order_by(Article.timestamp.desc()),
                           page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)

    next_url=url_for('blog.index', page=articles.next_num) \
        if articles.has_next else None
    prev_url=url_for('blog.index', page=articles.prev_num) \
        if articles.has_prev else None
    
    articles_with_tags, series_with_articles = get_articles_with_tags_series()
    
    return render_template('blog/blog.html', title=_('Blog'), articles = articles, articles_with_tags=articles_with_tags,
                           series_with_articles=series_with_articles, next_url=next_url, prev_url=prev_url, emptyForm=emptyForm)

@bp.route('/add', methods=['GET','POST'])
def add():
    if current_user.is_anonymous or not current_user.admin:
        flash(_('Insufficient Prvilege'))
        return redirect(url_for('blog.index'))
    form = BlogPostForm()
    if form.validate_on_submit():
        article = Article(title=form.title.data, body=form.body.data, update_timestamp=None, 
                          author = current_user, series = form.series.data, seriesOrder = form.seriesOrder.data)
        if form.submit.data:
            article.isSubmitted = True
        else:
            article.isSubmitted = False
        db.session.add(article)
        db.session.commit()
        tag_article(article,form.tags.data.split(','))
        db.session.commit()
        if form.submit.data:
            flash(_('Article has been submitted!'))
            return redirect(url_for('blog.article', id=article.id))
        else:
            flash(_('Article has been saved to drafts!'))
            return redirect(url_for('blog.edit', id=article.id))
    cache.clear()
    return render_template('blog/add_edit_blog.html', title = _('Add Blog Post'), form=form)



@bp.route('/article/<id>', methods=['GET','POST'])
def article(id):
    emptyForm = EmptyForm()
    commentForm = CommentForm()
    article = db.session.scalar(Article.fetch_article(id))
    if article is None:
        flash(_('The article you deleted could not be found'))
        return redirect(request.referrer)
    comments = db.session.scalars(article.fetch_approved_comments()).all()
    #Clear validators for username and email for loggedin users
    if current_user.is_authenticated:
        commentForm.username.validators = []
        commentForm.email.validators = []
    if commentForm.validate_on_submit():
        commentForm.comment.data = text_linkification(commentForm.comment.data)
        if current_user.is_authenticated:
            comment = Comment(comment=commentForm.comment.data, article=article, commenter=current_user, isApproved=True)
        else:
            comment = Comment(comment=commentForm.comment.data, article=article, 
                              name=commentForm.username.data, email=commentForm.email.data, isApproved=False)
        db.session.add(comment)
        db.session.commit()
        
        if current_user.is_anonymous:
            flash(_('Comment submitted for review. Your comment will be visible once approved'))
        else:
            flash(_('Comment added successfully'))

        redirect_url = url_for('blog.article', id = id )+"#articleComments"
        return redirect(redirect_url)

    articles_with_tags, series_with_articles = get_articles_with_tags_series()

    return render_template('blog/article.html', title=_(article.title), article=article, commentForm=commentForm, 
                           articles_with_tags=articles_with_tags, series_with_articles=series_with_articles, emptyForm = emptyForm,  comments=comments)

@bp.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    if current_user.is_anonymous or not current_user.admin:
        flash(_('Insufficient Prvilege'))
        return redirect(url_for('blog.index'))
    article = db.session.get(Article,id)
    if not article:
        flash('The article could not be found')
        return redirect(url_for('blog.index'))
    if current_user != article.author:
        flash('Only the original author can update the article')
        return redirect(url_for('blog.index'))
    form = BlogPostForm()
    stringTags = ""

    if form.validate_on_submit():
        article.title = form.title.data
        article.body = form.body.data
        article.update_timestamp = datetime.utcnow()
        article.series = form.series.data
        article.seriesOrder = form.seriesOrder.data
        articleTagList = db.session.scalars(article.tags.select()).all()
        if form.submit.data:
            article.isSubmitted = True
        else:
            article.isSubmitted = False
        for tag in articleTagList:
            article.untag(tag)

        #Let's put below in a method somewhere. It's shared with adding
        tag_article(article,form.tags.data.split(','))
        db.session.commit()
        if form.submit.data:
            flash(_('Article has been Edited!'))
            return redirect(url_for('blog.article', id=article.id))
        else:
            flash(_('Article has been saved to drafts!'))
            return redirect(url_for('blog.edit', id=article.id))
        
    elif request.method =='GET':
        form.title.data=article.title
        form.body.data=article.body
        form.series.data=article.series
        form.seriesOrder.data=article.seriesOrder
        articleTagList = db.session.scalars(article.tags.select()).all()
        for tag in articleTagList:
            if stringTags == "":
                stringTags = tag.name
            else:
                stringTags += ", "+ tag.name
        form.tags.data = stringTags
    cache.clear()
    return render_template('blog/add_edit_blog.html', title = _('Edit Blog Post'), form=form)


@bp.route('/delete/<id>', methods=['GET', 'POST'])
def delete(id):
    if current_user.is_anonymous or not current_user.admin:
        flash(_('Insufficient Prvilege'))
        return redirect(url_for(request.referrer))
    form = EmptyForm()
    if form.validate_on_submit():
        article = db.session.get(Article,id)
        if article is None:
            flash(_('The article you deleted could not be found'))
            return redirect(url_for('blog.index'))
        article.delete()
        db.session.commit()
        flash(_('You have successfully deleted the article!'))
        cache.clear()
        return redirect(url_for('blog.index'))

@bp.route('/delete-comment/<c_id>', methods=['POST'])
def delete_comment(c_id):
    form = EmptyForm()
    if form.validate_on_submit():
        comment = db.session.get(Comment, c_id)
        if comment is None:
            flash(_('The comment you deleted could not be found'))
            return redirect(request.referrer)
        comment.delete()
        db.session.commit()
        flash(_('You have successfully deleted the comment!'))
        return redirect(request.referrer)

@bp.route('/tag/<tag>', methods=['GET'])
def tag(tag):
    tag = db.session.scalar(sa.select(Tag).filter_by(name=tag))
    emptyForm = EmptyForm()
    page = request.args.get('page', default=1, type=int)
    articles = db.paginate(tag.tagged_submiited_articles_select().order_by(Article.timestamp.desc()),
     page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    
    next_url=url_for('blog.tag', tag=tag, page=articles.next_num) \
        if articles.has_next else None
    prev_url=url_for('blog.tag', tag=tag, page=articles.prev_num) \
        if articles.has_prev else None

app/templates/blog/_articleAdminOptions.html
<a href="{{ url_for('blog.edit', id = article.id) }}" class="btn btn-outline-primary btn-sm me-2">Edit</a>
<a class="btn btn-outline-danger btn-sm" href="#deleteModal{{ article.id }}" data-bs-toggle="modal">Delete</a>

<!--Delete Modal-->
<div class="modal fade" id="deleteModal{{ article.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">{{ _('Confirm Delete') }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
            </div>
            <div class="modal-body">
                {{ _('Are you sure you want to delete this post?') }} <br><br>
                <div class="vr"></div>
                {{ article.body|safe| truncate(500) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _('Close') }}</button>
                <form action="{{ url_for('blog.delete', id = article.id) }}" method="post">
                    {{ emptyForm.hidden_tag() }}
                    {{ emptyForm.submit(value=_('Delete'), class="delete btn btn-outline-danger") }}
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/blog/_article_info.html
<div class="articleTitle text-break">
    <h1>
        <a href="{{ url_for('blog.article', id=article.id) }}">{{ article.title }}</a>
        {% if not article.isSubmitted %}
        <span class="badge text-bg-secondary">Draft</span>
    {% endif %}
    </h1>
    
</div>
<div class="articleMetadata mb-2">
    <i>Posted by</i> {{ article.author.username }} on {{ moment(article.timestamp).format("MM/DD/YYYY") }} under
    {% for tag in articles_with_tags[article.id] %}
        <a href="{{ url_for('blog.tag', tag=tag) }}" class="btn btn-outline-primary btn-sm" id="articleTagBadge">{{ tag }}</a>
    {% endfor %}
</div>
{% if current_user.admin %}
<div class="articleAdmin d-flex">
    <a href="{{ url_for('blog.edit', id = article.id) }}" class="btn btn-outline-primary btn-sm me-2">Edit</a>
    <a class="btn btn-outline-danger btn-sm" href="#deleteArticleModal{{ article.id }}" data-bs-toggle="modal">Delete</a>
</div>
{% endif %}

<!--Delete Modal-->
<div class="modal fade" id="deleteArticleModal{{ article.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">{{ _('Confirm Delete') }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
            </div>
            <div class="modal-body">
                {{ _('Are you sure you want to delete this post?') }} <br><br>
                <div class="vr"></div>
                {{ article.body|safe| truncate(500) }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _('Close') }}</button>
                <form action="{{ url_for('blog.delete', id = article.id) }}" method="post">
                    {{ emptyForm.hidden_tag() }}
                    {{ emptyForm.submit(value=_('Delete'), class="delete btn btn-outline-danger") }}
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/blog/_article_overview.html
<div class="article">
    <div class="articleInfo">
        {% include "blog/_article_info.html" %}
    </div>
    {% if article.series %}
        {% include "blog/_series.html" %}
    {% endif %}
    <div class="articleBody text-break">{{ article.body|safe| truncate(1000, False, '...' , 300) }}</div>
    <div class="d-flex justify-content-between">
        <a href="{{ url_for('blog.article', id=article.id) }}" class="btn btn-outline-primary">Read More</a>
        <a href="{{ url_for('blog.article', id=article.id) + '#comments' }}" class="btn btn-outline-secondary">Comments ({{article.count_approved_comments()}})</a>
    </div>

</div>

app/templates/blog/_comment.html
<div class="d-flex mb-4 mt-3 comment">
    <div class="flex-shrink-1 me-2 commentAvatar">
        {% if comment.commenter %}
        <img class="avatarImg" src = "{{ comment.commenter.avatar(36) }}">
        {% else %}
        <img class="avatarImg" src = "{{ anonymous_avatar(36, comment.email) }}">
        {% endif %}
    </div>
    <div class="flex-grow-1">
        
        {% set user_link %}
        {% if comment.commenter %}
        <a href = "{{ url_for('main.user', username=comment.commenter.username) }}">
            {{ comment.commenter.username }}
        </a> 
        {% else %}
        {{ comment.name }}
        {% endif %}
        {% endset %}
        {{ _('%(username)s said %(when)s:', 
            username=user_link, when = moment(comment.timestamp).fromNow()) }}  
        
        <div id="comment{{ comment.id }}" class="text-break comment">
            {{ comment.comment|textile|safe }}
        </div>
        
    </div>
    <!--3 dot contextual menu-->
    {% if current_user.is_authenticated %}
    <div class="flex-shrink-1">
        <div class ="dropdown">
            <a class="dropdown-toggle" id="postDropDownMenuLink" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-three-dots-vertical"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="postDropDownMenuLink">
                {% if current_user == comment.commenter %}
                <li><a class="dropdown-item" href="#deleteCommentModal{{ comment.id }}" data-bs-toggle="modal">{{ _('Delete') }}</a></li>
                {% elif comment.commenter and current_user.is_authenticated and current_user.is_following(comment.commenter) %}
                <form action="{{ url_for('main.unfollow', username=comment.commenter.username) }}" method="post">
                    {{ emptyForm.hidden_tag() }}
                    {{ emptyForm.submit(value=_("Unfollow " + comment.commenter.username), class="dropdown-item") }}
                </form>
                {% elif comment.commenter and current_user.is_authenticated and not current_user.is_following(comment.commenter) and not comment.commenter.isTempAccount%}
                <form action="{{ url_for('main.follow', username=comment.commenter.username) }}" method="post">
                    {{ emptyForm.hidden_tag() }}
                    {{ emptyForm.submit(value=_("Follow " + comment.commenter.username), class="dropdown-item") }}
                </form>
                {% endif %}
            </ul>
        </div>
    </div>
    {% endif %}
</div>

<!--Delete Modal-->
<div class="modal fade" id="deleteCommentModal{{ comment.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">{{ _('Confirm Delete') }}</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cancel"></button>
            </div>
            <div class="modal-body">
                {{ _('Are you sure you want to delete this comment?') }} <br><br>
                <div class="vr"></div>
                {{ comment.comment }} 
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ _('Close') }}</button>
                <form action="{{ url_for('blog.delete_comment', c_id = comment.id) }}" method="post">
                    {{ emptyForm.hidden_tag() }}
                    {{ emptyForm.submit(value=_('Delete'), class="delete btn btn-outline-danger") }}
                </form>
            </div>
        </div>
    </div>
</div>

app/templates/blog/_series.html
<h2>{{ article.series }} Series:</h2>
<ul>
{% for a in series_with_articles[article.series] %}
<div id="seriesLink">
    <li><a href="{{ url_for('blog.article', id=a.id ) }}">{{ a.title }}</a></li>
</div>
{% endfor %}
</ul>
<br>

app/templates/blog/_sidebar.html
<div id="sidebar">
    <div class="card">
        <div class="card-header">About Chris</div>
        <div class="card-body d-flex flex-column">{% include "_sidebar_AboutChris.html" %}</div>
    </div>
    <div class="card" id="tags">
        <div class="card-header">Tags/Categories</div>
        <div class="card-body d-flex flex-column">
            {% for tag in g.get('all_tags',{}) %}
            <div class="tag mb-2 d-flex justify-content-center">
                <div class="tag-button">
                    <a href="{{ url_for('blog.tag', tag=tag.name) }}">{{ tag.name }}({{ tag.count_articles() }})</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

app/templates/blog/add_edit_blog.html
{% extends "base.html" %}

{% block content %}

<div class="warpper" style="width: 700px; margin: auto">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <!--title-->
        <div class="form mb-3">
        {{ form.title.label() }}
        {{ form.title(class="form-control", id="blogPostTitle") }}
        </div>
        {% for error in form.title.errors %}
        <span style="color:red;">{{ error }}</span><br>
        {% endfor %}
        <!--body-->
        <div class="form mb-3">
        {{ form.body.label("Blog Post Body") }}
        {{ form.body() }}
        </div>
        {% for error in form.body.errors %}
        <span style="color:red;">{{ error }}</span><br>
        {% endfor %}
        <!--Tags-->
        <div class="form mb-3">
        {{ form.tags.label() }}
        {{ form.tags(class="form-control", id="blogPostTags") }}
        </div>
        {% for error in form.tags.errors %}
        <span style="color:red;">{{ error }}</span><br>
        {% endfor %}
        <!--Series Name-->
        <div class="form mb-3">
        {{ form.series.label() }}
        {{ form.series(class="form-control", id="seriesName") }}
        </div>
        {% for error in form.series.errors %}
        <span style="color:red;">{{ error }}</span><br>
        {% endfor %}
        <!--Series Order-->
        <div class="form mb-3">
        {{ form.seriesOrder.label() }}
        {{ form.seriesOrder(class="form-control", id="seriesName") }}
        </div>
        {% for error in form.seriesOrder.errors %}
        <span style="color:red;">{{ error }}</span><br>
        {% endfor %}

        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <!--Save -->
            {{ form.save(class="btn btn-outline-primary") }}
            <!--Submit-->
            {{ form.submit(class="btn btn-outline-primary") }}
        </div>
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name="body") }}
</div>


{% endblock %}

app/templates/blog/article.html
{% extends "base.html" %}

{% block content %}

<div class="row">
    <div class="col-md-9">
        <div class="articleInfo">
            {% include "blog/_article_info.html" %}
        </div>
        <hr>
        {% if article.series %}
        {% include "blog/_series.html" %}
        {% endif %}
        {{ ckeditor.load_code_theme() }}
        <div class="articleBody text-break">{{ article.body|safe }}</div>
        <br>
        <hr>
        <br>
        <div id="comments">
            <h1>{{ _('Comments') }}</h1>
            <br>
            <!--Comment Submission Form-->
            <form action="" method="post">
                {{ commentForm.hidden_tag() }}
                {% if current_user.is_anonymous %}
                <div class="form-floating mb-3">
                    {{ commentForm.username(class="form-control", id="floatingInput", placeholder="Name") }}
                    {{ commentForm.username.label(for="floatingInput") }}
                    {% for error in commentForm.username.errors %}
                    <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="form-floating mb-3">
                    {{ commentForm.email(class="form-control", id="floatingInput", placeholder="Email") }}
                    {{ commentForm.email.label(for="floatingInput") }}
                    {% for error in commentForm.email.errors %}
                    <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
                <div class="form-floating mb-3">
                    {{ commentForm.comment(class="form-control", id="floatingInput", placeholder="Comment") }}
                    {{ commentForm.comment.label(for="floatingInput") }}
                    {% for error in commentForm.comment.errors %}
                    <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <p>
                        {{ commentForm.submit(class="btn btn-outline-primary") }}
                    </p>
                </div>
            </form>
            <!--Comments-->
            {% if comments %}
            <div id="articleComments">
                {% for comment in comments %}
                    {% include "blog/_comment.html" %}
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="col-md-3">
        {% include "blog/_sidebar.html" %}
    </div>
    
</div>

{% endblock %}

app/templates/blog/blog.html
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-9">
    {% if current_user.admin %}
    <div class="d-flex justify-content-end">
        <a class="btn btn-outline-primary" href="{{ url_for('blog.add') }}">Post Article</a>
    </div>
    {% endif %}
    {% for article in articles %}
        {% include "blog/_article_overview.html" %}
        <hr>
    {% endfor %}
    {% include "_pagination.html" %}
    </div>
    <div class="col-md-3">
        {% include "blog/_sidebar.html" %}
    </div>
    
</div>



{% endblock %}